### PR TITLE
Generate TypeScript declarations

### PR DESCRIPTION
**Pull request by stephenmathieson**

### CODE REVIEW

**Comment by ckundo** [comment]
what does this do, and how will it be used?

**Comment by stephenmathieson** [comment]
Refer to the title.

The TypeScript compiler will now emit TypeScript definition files which will be included when you `npm install auto-vo`. This enables TypeScript projects to use this library.

**Comment by ckundo** [comment]
didn't realize i needed to publish type definitions for the library to be imported in a TS project. or do you mean to enable TypeScript features?

**Comment by stephenmathieson** [comment]
Yes, the type definitions need to be published. Right now, only `.js` files are included in the package. The TypeScript compiler doesn't have any idea what is exported as result.

VSCode complaining about importing this module

**Comment by ckundo** [comment]
ah I see, since it's being published as transpiled js. what about simply including the .ts files with their exports in the package?

**Comment by ckundo** [comment]
thanks @stephenmathieson

**Comment by stephenmathieson** [comment]
> ah I see, since it's being published as transpiled js. what about simply including the .ts files with their exports in the package?

This won't work, as the `main` field in `package.json` doesn't (and cannot) point to a TypeScript file, and that's how TypeScript figures out what `import thing from 'thing'` means.

The correct way to do this is by emitting `*.d.ts` files along with `*.js` files and including them in your distributable.

**Comment by ckundo** [comment]
@stephenmathieson should the generated `*.d.ts` files be git ignored, but still published?

**Comment by stephenmathieson** [comment]
Yes, that's generally what folks do. Any code that's generated can be git ignored.

Would you like me to make that change?

**Comment by ckundo** [comment]
@stephenmathieson nope, I can push the `.gitignore` in a sec. thanks!

**Comment by ckundo** [comment]
published in `v1.2.1`

**Comment by stephenmathieson** [comment]
It works!

VSCode auto-completion with version v1.2.1

**Pull request merged**
